### PR TITLE
Implement rety

### PR DESCRIPTION
**Pull request by omo**
If you did a mistyping, the phrase comes again in the
same session.

### CODE REVIEW

**Comment by omo** [comment]
@karino2 This is the last one I had in my mind so far.

**Comment by karino2** [comment]
Thanks, it seems working on my phone.  I've released as Ver 1.5.
If you have some initializeAsJapanese texts idea, please update it too! (I feel current texts contain too much location name...)

**Comment by omo** [comment]
I don't have any particular idea.
We could do some counting and find fewer used letters, and pick words containing them.
Well, saying is easier than doing :-)

**Comment by omo** [comment]
Anyway, thanks  for merging!

**Pull request merged**
